#
# = bio/output/html/alignment.rb - HTML alignment output
#
# Copyright::  Copyright (C) 2010 Pjotr Prins <pjotr.prins@thebird.nl>
#
# License::    The Ruby License
#

module Bio::Html

  class HtmlAlignment

    # == Description
    #
    # Create HTML colorized alignments from an Alignment object.
    # Extra information below the alignment, like evidence for
    # positive selection, can be added.
    #
    # == Examples
    #
    # Show evidence of positive selection pressure, as calculated
    # by PAML's codeml
    #
    #--
    # The following few lines are not shown in the rdoc documentation
    #
    #   >> require 'bio'
    #   >> require 'bio/test/biotestfile'
    #   >> buf = BioTestFile.read('paml/codeml/models/results0-3.txt')
    #   >> alnbuf = BioTestFile.read('clustalw/example1.aln')
    #++
    #
    # alnbuf contains the contents of a Clustal alignment file
    #
    #   >> include Bio
    #   >> aln = ClustalW::Report.new(alnbuf)
    #
    # Instantiate an HtmlAlignment object 
    #
    #   >> simple = Html::HtmlAlignment.new(aln.alignment, :title => "Clustal")
    #   >> html = simple.html()
    #
    # Ascertain we have a result
    #
    #   >> html[8..58]
    #   => "<pre>\nquery                                   -MKNT"
    #
    # Write it to a file (for viewing)
    #
    #   #> File.open('test.html','w') {|f| f.write(html) }
    # 
    #   >> colored = Html::HtmlAlignment.new(aln.alignment, :scheme => ColorScheme::Zappo)
    #   # !> colored.add_positive_sites(codeml_positive_sites)
    #   >> html = colored.html
    #   >> File.open('test.html','w') {|f| f.write(html) }
    #   #> "xxx"
    # 
    # Invoke Bioruby's PAML codeml parser, after having read the contents
    # of the codeml result file into _buf_ (for example using File.read)
    #
    #   !> codeml = PAML::Codeml::Report.new(buf)
    #

    # Instantiate HtmlAlignment object where _alignment_ is a Bio::Alignment
    # type object.
    #
    # Supported options are
    #
    #   :title       The title
    #   :scheme      Color scheme (default Bio::ColorScheme::Zappo)
    #
    def initialize alignment, options = {}
      @alignment = alignment
      @options = options
    end

    # Show a section title
    def title
      return @options[:title] if @options[:title]
      ''
    end

    # Return credits in footer
    def footer
      scheme = @options[:scheme]
      ret = ''
      ret += scheme.html_help if scheme
      ret += 'Generated by Bioruby Bio::HtmlAlignment'
      ret += ' ('+scheme.to_s+')' if scheme
      ret
    end

    # Return the consensus line (match_line)
    def consensus 
      @alignment.match_line
    end

    # HTML generator (color support planned for)
    #
    # Supported options _opts_ are 
    #
    #   :no_title      Don't show title
    #   :no_footer     Don't show footer
    def html(opts = { :ljust => 40 })
      if @options[:scheme]
        html_color(opts)
      else
        html_simple(opts)
      end
    end

    # The most simple form of HTML generator.
    #
    # Options can be set:
    #
    #   :ljust         Left adjust description/id (default 40)
    #
    # For the more supported options see html.
    def html_simple opts
      ljust = opts[:ljust]
      ret = ''
      ret += title+"\n" if not opts[:no_title]
      ret += "<pre>\n"
      @alignment.each_pair do | id, seq |
        ret += id.ljust(ljust)+seq+"\n"
      end
      ret += "Consensus".ljust(ljust)+consensus
      ret += "\n</pre>"
      ret += footer if not opts[:no_footer]
      ret
    end

    # The color HTML generator.
    #
    # For the supported options see html
    def html_color opts
      ret = ''
      ret += title+"\n" if not opts[:no_title]
      ret += '<p /><font face="courier"><table>'+"\n"
      @alignment.each_pair do | id, seq |
        h = Html::HtmlSequence.new(seq)
        ret += '<tr><td>'+id+'</td><td>'+h.html_color+"</td></tr>\n"
      end
      ret += '<tr><td>Consensus</td><td>'+consensus.gsub(/\s/,'&nbsp;')+"</td></tr>\n"
      ret += "\n</table></font><p />"
      ret += footer if not opts[:no_footer]
      ret
    end

  end # Alignment

end # Bio::Html


